# Generated by Django 5.2 on 2026-02-19 16:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Modelo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='UnidadeMedida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Nome', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Medicao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Tipo', models.CharField(max_length=30)),
                ('UnidadeMedidaId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api_telemetria.unidademedida')),
            ],
        ),
        migrations.CreateModel(
            name='Veiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Descricao', models.CharField(max_length=255)),
                ('Ano', models.IntegerField(max_length=4)),
                ('Horimetro', models.IntegerField(max_length=2)),
                ('MarcaId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api_telemetria.marca')),
                ('ModeloId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api_telemetria.modelo')),
            ],
        ),
        migrations.CreateModel(
            name='MedicaoVeiculo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Data', models.DateTimeField()),
                ('Valor', models.FloatField()),
                ('MedicaoId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api_telemetria.medicao')),
                ('VeiculoId', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='api_telemetria.veiculo')),
            ],
        ),
    ]
