# Generated by Django 5.2 on 2026-02-27 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api_telemetria', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='veiculo',
            name='Ano',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='veiculo',
            name='Horimetro',
            field=models.IntegerField(),
        ),
    ]
